name: Build DLL with MSBuild (.NET Framework 4.7.2)

on: [push, pull_request]

env:
  Solution_Name: MU3Input.sln
  Project_Path: MU3Input/MU3Input.csproj
  Output_Directory: build
  SolutionDir: ..\


jobs:
  build:
    runs-on: windows-latest  # Windows 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 拉取代码

      - name: Install .NET Framework 4.7.2 Developer Pack
        run: choco install netfx-4.7.2-devpack -y

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2  # 配置 MSBuild

      - name: Restore NuGet packages
        run: nuget restore ${{ env.Solution_Name }}

      - name: Build DLL using MSBuild
        run: msbuild ${{ env.Project_Path }} /p:Configuration=Release /p:Platform=x64 /p:OutputPath=build
 
      - name: Show path
        run: ls

      - name: Install ILMerge
        run: choco install ilmerge -y

      - name: Merge DLL
        run: ilmerge /out:build/MU3Input_merged.dll /target:library build/MU3Input.dll build/*.dll /wildcards /internalize /log

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: Built-DLL
          path: .\*

